# A sample Gemfile
source "https://rubygems.org"

gem "sinatra"
gem "sinatra-contrib"
gem "puma"
gem "oauth2"
gem "dotenv"
gem "httparty"
gem "activerecord"
gem 'sinatra-activerecord' # excellent gem that ports ActiveRecord for Sinatra
gem "rake"

group :development, :test do
  gem 'sqlite3'
end

group :development do
  gem "pry"
  gem "awesome_print"
  gem "benchmark-ips"
  gem "foreman"
end

group :production do
  gem 'pg' # this gem is required to use postgres on Heroku
end
